### ISSUE TITLE
RCA Preamplifier

### ISSUE THREAD

**Issue by KrakenReef** [Audio-Injector/AudioInjector-Analogue-Breakout-Standard#1]
Hello.

I have a doubt regarding the RCA Preamplifier. Is this preamp valid to use with Audioinjector Stereo soundcard?
How can i connect it to my audioinjector stereo board?

Thanks in advance.
Regards.

**Comment by flatmax** [comment]
The low cost sound cards don't support the AI-ABS which is the analogue breakout standard.

The Isolated soundcard does support the AI-ABS. The soon to be manufactured Pro. sound card also does.

**Comment by KrakenReef** [comment]
Thanks flatmax!
